modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/Mrbysco/NeoAuth/issues"
license="MIT"

[[mods]]
modId="neo_auth"
version="${file.jarVersion}"
displayName="NeoAuth"
displayURL="https://www.curseforge.com/minecraft/mc-mods/neoauth"
authors="Mrbysco, Axieum"
credits="Axieum for making Auth Me"
description='''
A Neoforge port of AuthMe
'''
[[dependencies.neo_auth]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.neo_auth]]
modId="forge"
mandatory=true
versionRange="[47.1.0,)"
ordering="NONE"
side="BOTH"